# Generated by Django 5.0.1 on 2024-01-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(blank=True, max_length=100)),
                ('Employee_id', models.CharField(max_length=100, unique=True)),
                ('Official_mail', models.CharField(blank=True, max_length=100)),
                ('Employee_contact_info', models.CharField(blank=True, max_length=100)),
                ('Reporting_manager', models.CharField(blank=True, max_length=100)),
                ('Data_security', models.CharField(blank=True, max_length=100)),
                ('Accessories_Given', models.CharField(blank=True, max_length=100)),
                ('Notes', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
