# Generated by Django 5.0.1 on 2024-01-05 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('Asset_name', models.CharField(blank=True, max_length=100)),
                ('Asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Description', models.CharField(blank=True, max_length=100)),
                ('sap_id', models.CharField(blank=True, max_length=100)),
                ('Serial_Number', models.CharField(max_length=100, unique=True)),
                ('Manufacturer', models.CharField(blank=True, max_length=100)),
                ('Model', models.CharField(blank=True, max_length=100)),
                ('Purchase_Date', models.DateField(blank=True, null=True)),
                ('Purchase_Cost', models.CharField(blank=True, max_length=100)),
                ('Location', models.CharField(blank=True, max_length=100)),
                ('Status', models.CharField(blank=True, max_length=100)),
                ('Anti_virus_status', models.CharField(blank=True, max_length=100)),
                ('Warranty_Information', models.CharField(blank=True, max_length=100)),
                ('License_or_Subscription', models.CharField(blank=True, max_length=100)),
                ('Notes', models.CharField(blank=True, max_length=100)),
                ('Vendors_Name', models.CharField(blank=True, max_length=100)),
                ('Vendors_information', models.CharField(blank=True, max_length=100)),
                ('Vendors_location', models.CharField(blank=True, max_length=100)),
                ('Vendors_contact_no', models.CharField(blank=True, max_length=100)),
                ('Vendors_email_id', models.CharField(blank=True, max_length=100)),
                ('display_asset_condition_before', models.ImageField(blank=True, null=True, upload_to='')),
                ('display_asset_condition_after', models.ImageField(blank=True, null=True, upload_to='')),
                ('invoice_details', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssetProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_value', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.asset')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.property')),
            ],
        ),
    ]
